### ISSUE TITLE
might be able to help in some way

### ISSUE THREAD

**Issue by vanoak** [Zylann/godot_heightmap_native_plugin#15]
Hi,

I'm very interested in having this plug-in feature complete and most likely enhanced further, so although I'm not a low-level coder any help you need for testing, documentation or similar, let me know, I might be able to help.

Do you have some kind of development roadmap?

Thanks and good job!

**Comment by Zylann** [comment]
For now, basically all issues in the tracker, and the main ones are quite low level since they need engine features. I'm currently trying to find a workaround for saving...

**Comment by Zylann** [comment]
I'll close this issue since there isn't much of an... issue^^ feel free to contribute stuff one day if you want to
