### ISSUE TITLE
Painting not accurate at times

### ISSUE THREAD

**Issue by christoffersch** [Zylann/godot_heightmap_native_plugin#36]
Yesterday it seemed fine, but now when I paint, it's not accurate to where I aim the mouse.
Video attached:

https://streamable.com/wm5so

**Comment by Zylann** [comment]
Did you scale the root node? The terrain doesn't support Transform scaling at the moment.

**Comment by christoffersch** [comment]
Don't think I scaled anything 🐙 

Here's a project file for you:
[https://we.tl/xte3GcVIHW](url)

**Comment by Zylann** [comment]
Looks like you ended up with mismatching map sizes. The normalmap and heightmap are 2049x2049, but splatmap and detailmaps are 513x513.
Which steps did you do to get into this state?

**Comment by christoffersch** [comment]
@Zylann woops, that seems to make sense. I don't even know how to change the resolution of the splat-, color- and detailmaps though!

I figure it all get a little messy since I used your demo terrain and imported it into my own project; I couldn't figure out how to create a HTerrain of my own.

I suppose this is not a bug then ;)

**Comment by Zylann** [comment]
It's a bug if you didn't actively changed the resolutions of the images using a image editor :D

**Comment by christoffersch** [comment]
I'll let you know if things get weird again! Right now, it seems alright.

Maybe you could do a few instructions on how to create a terrain, 'cause I really sat for like an hour trying to figure it out, until I just decided to copy-paste yours

**Comment by Zylann** [comment]
I just pushed a fix for resizing, so hopefully that issue shouldn't happen again.

The way to create a new terrain using Godot 3.0.2 is not going to stay like that, but I'll write it here:

1) Create a new HTerrainData resource in the inspector
2) Save it as a .tres file
3) Create a HTerrain node
4) Select its `data` property, and load the .tres resource you saved earlier. Doing that should make a terrain appear. If you can't see it, make sure you have a light or an environment in your scene.
5) Change the resolution if needed, then click the Heightmap menu --> Save

And that should be it.
To give you an idea, after the Godot changes I need get solved, those steps will simply be:

1) Create a new HTerrain node: a new terrain will apear
2) The node will have a warning sign next to it until you select a folder to save its data. Click on the `data_directory` property, and select where terrain data will be saved.
3) Save your scene with Ctrl+S

:D

**Comment by Zylann** [comment]
I wrote a documentation stub just for this: https://github.com/Zylann/godot_heightmap_native_plugin/blob/master/addons/zylann.hterrain/doc/main.md

I'll close the issue for now, let me know if it happens again.
