### ISSUE TITLE
Cant load the game if using Hterrain

### ISSUE THREAD

**Issue by katznboyz1** [Zylann/godot_heightmap_native_plugin#49]
Here is the issue: https://i.redd.it/vwwv0ajghml11.png

**Comment by Zylann** [comment]
Do you have a project reproducing the issue?

**Comment by katznboyz1** [comment]
Yes, I do

**Comment by Zylann** [comment]
Can you provide a link to this project so I can have a look?

**Comment by katznboyz1** [comment]
Im not sure how to send all the files to you, is there a specific file that I should send, and if so, what is the name?

**Comment by Zylann** [comment]
It should be a simple project that I can launch and walk through to see what's going on, because I need to know how to reproduce the bug.

**Comment by katznboyz1** [comment]
Ok they are uploading to dropbox now

**Comment by katznboyz1** [comment]
Ok dropbox wont work, I don't know how I can send these files.

**Comment by katznboyz1** [comment]
[gd_scene load_steps=8 format=2]

[ext_resource path="res://lumberjack.gd" type="Script" id=1]
[ext_resource path="res://data/3d-objects/lumberJack.obj" type="ArrayMesh" id=2]
[ext_resource path="res://addons/zylann.hterrain/hterrain.gd" type="Script" id=3]
[ext_resource path="res://addons/zylann.hterrain/tools/icons/icon_heightmap_node.svg" type="Texture" id=4]
[ext_resource path="res://data/terrain/terraindata.tres" type="Resource" id=5]
[ext_resource path="res://data/textures/grass-texture-2.jpg" type="Texture" id=6]

[sub_resource type="BoxShape" id=1]

extents = Vector3( 0.20593, 1, 0.240223 )

[node name="Spatial" type="Spatial" index="0"]

[node name="lumberjack" type="KinematicBody" parent="." index="0"]

editor/display_folded = true
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 36.6415, 0 )
input_ray_pickable = true
input_capture_on_drag = false
collision_layer = 1
collision_mask = 1
axis_lock_linear_x = false
axis_lock_linear_y = false
axis_lock_linear_z = false
axis_lock_angular_x = false
axis_lock_angular_y = false
axis_lock_angular_z = false
collision/safe_margin = 0.001
script = ExtResource( 1 )

[node name="MeshInstance" type="MeshInstance" parent="lumberjack" index="0"]

layers = 1
material_override = null
cast_shadow = 1
extra_cull_margin = 0.0
use_in_baked_light = false
lod_min_distance = 0.0
lod_min_hysteresis = 0.0
lod_max_distance = 0.0
lod_max_hysteresis = 0.0
mesh = ExtResource( 2 )
skeleton = NodePath("..")
material/0 = null
_sections_unfolded = [ "Transform" ]

[node name="CollisionShape" type="CollisionShape" parent="lumberjack" index="1"]

shape = SubResource( 1 )
disabled = false

[node name="world" type="Spatial" parent="." index="1"]

transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -100, 0, -100 )
script = ExtResource( 3 )
_sections_unfolded = [ "Transform" ]
__meta__ = {
"_editor_icon": ExtResource( 4 )
}
collision_enabled = true
async_loading = false
ambient_wind = 0.0
lod_scale = 2.0
map_scale = Vector3( 1, 1, 1 )
data = ExtResource( 5 )
chunk_size = 16
shader_type = "Classic4"
custom_shader = null
shader_params/u_ground_uv_scale = 20
shader_params/u_depth_blending = true
shader_params/u_triplanar = null
ground/albedo_bump_0 = ExtResource( 6 )
ground/normal_roughness_0 = null
ground/albedo_bump_1 = null
ground/normal_roughness_1 = null
ground/albedo_bump_2 = null
ground/normal_roughness_2 = null
ground/albedo_bump_3 = null
ground/normal_roughness_3 = null
_detail_objects_data = [  ]

**Comment by katznboyz1** [comment]
That is my world.tcsn file

**Comment by Zylann** [comment]
How large is the project? You can try to zip it and drag it to Github. If it's too big, try https://framadrop.org/.
If it still doesn't work... then start the editor from scratch, reproduce the bug and send me the console log. I need to understand which steps you took to get the bug

**Comment by katznboyz1** [comment]
https://framadrop.org/r/gHbWhrTRxg#z+58GyZEYV932QcU6xSsJhi4aviHumyDlZ8VpYgqruo=

**Comment by Zylann** [comment]
Your terrain data was never saved, so it looks like you hit issue #4: currently terrains are not saved when you save the scene. 
When you create a terrain, you have to save it by using the Terrain->Save menu:
![image](https://user-images.githubusercontent.com/1311555/45381940-aa670900-b5fe-11e8-85f5-339e83960c73.png)

To fix your project, you can recreate the terrain by going through those steps: https://github.com/Zylann/godot_heightmap_native_plugin/blob/master/addons/zylann.hterrain/doc/main.md
