### ISSUE TITLE
Terrain data is not exported automatically

### ISSUE THREAD

**Issue by DigitalMonkeyPa1** [Zylann/godot_heightmap_native_plugin#50]
To me, the terrain worked fine in the editor, but in exported game terrain didn't show up. I tried to peek into the .pck file to find any missing files, but no PCK viewer/extractor is compatible with Godot's PCK format.
Then I opened the PCK file in notepad++ and searched for files in terrain folder, then I found that "height.bin" is not there, so I tried adding a filter to include *.bin files in export options in Godot, and it worked.

I know that this is not an issue in the plugin, but I thought it would be a good point to mention.
Perhaps an easy workaround here is to use ".res" instead of ".bin", as Godot exports .res files, so users need not have to remember adding filters to all export configurations for all projects that use this plugin.

By the way, Godot 3.1 alpha has been released, have you tested the new features that you have been waiting for, is saving automatic now.

Also, I like to contribute to documentation, do you think it's the right time for documentation or wait for some more time.

If possible I will try to make some cool screenshots of terrains with trees, river, waterfall, rocks, grass....etc, to showcase.

**Comment by Zylann** [comment]
Yeah this is another reason why I wanted this in 3.1: https://github.com/godotengine/godot/pull/19501
Godot has no loader and no saver for heightmap formats and I want to be able to define it from my plugin, but so far only GDNative can do this for some odd reason.

I've been waiting for devs feedback for very long and 3.1 entered feature freeze so despite it being a request I made long ago, it might still not make it for 3.1... wait and see.

**Comment by DigitalMonkeyPa1** [comment]
So till that PR is accepted, can you store height data in a ".res" file instead of ".bin", because, with current implementation of export process, the export filter has to be added to every export type (like win-32-debug, win32-release, ...win64-..., ... linux-32-debug, ... linux-64, ..., html5, android, ..mac, .... ) individually for each project that uses terrain.

I know the reason for export filters is to handle situations like this, but it's clumsy.

I think the plugin is ready for use in games (Proof: I released a game with a terrain, really), so you can just go on with some hacks until Godot gets better.

**Comment by Zylann** [comment]
Just changing the extension to .res might do the trick, but none of the PoolVectors support the data type that comes in that file (half floats). You can try, tell me if that works^^
If the loaders PR is postponed I might have a worst case scenario hack in mind involving saving as a PNG R8G8 (where each pixel has 16 bits but actually representing 16 bit floats). That may hurt loading memory and performance internally but at least it will ease usage.

**Comment by Zylann** [comment]
Should be solved by cd9a5ed8293be1c572873bab5bd8c2bb8e83e1f5
